# Generated by Django 2.1.4 on 2019-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
