# Generated by Django 2.1.4 on 2019-03-12 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190312_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='readnum',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
