# Generated by Django 2.1.4 on 2019-03-13 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190313_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnum',
            name='created_date',
            field=models.DateField(verbose_name=datetime.date(2019, 3, 13)),
        ),
    ]
