# Generated by Django 2.1.4 on 2019-03-13 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_readdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
